version: '3'

services:

  mongo:
    image: "mongo:4.2.17-bionic"
    ports:
      - "64001:27017"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_INITDB_DATABASE: "logs"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - ./db-data/mongo/:/data/db